### ISSUE TITLE
[ADAP-498] [Bug] BQ does not retry on 503

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-bigquery#682] opened 2023-04-26 17:50 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Current if BigQuery returns a 503 error we do not retry even though BigQuery recommends that as the course of action.

### Expected Behavior

This is not a regression but rather an oversight -- 503 errors should be both retryable and reopenable since it indicates a transient unavailable condition in BigQuery

### Steps To Reproduce

Transient -- requires intermittent error from BQ.

### Environment

```markdown
- dbt-core: all 
- dbt-bigquery: all
```

**Comment by dbeatty10** [comment] 2023-04-27 13:29
Thanks for reaching out @barberscott !

We'll put this in our queue.

The solution might be as simple as adding [`google.cloud.exceptions.ServiceUnavailable`](https://github.com/googleapis/python-api-core/blob/2a6a36bd820e1344c8b2526eb75d0b9f3a055d3b/google/api_core/exceptions.py#L409-L414) to the list here:

https://github.com/dbt-labs/dbt-bigquery/blob/7c216445f8009baa9cec4d61dd56693be1dd79fa/dbt/adapters/bigquery/connections.py#L53-L59

**Comment by jx2lee** [comment] 2023-12-18 12:40
@dbeatty10 
I created an instance of ServiceUnavailable and ran the test code ([test_is_retryable](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/tests/unit/test_bigquery_connection_manager.py#L81)).

Current: Not added ServiceUnavailable on `RETRYABLE_ERRORS`.
Result: Test passed.

```
def test_is_retrievable(self):
        _is_retryable = dbt.adapters.bigquery.connections._is_retryable
        exceptions = dbt.adapters.bigquery.impl.google.cloud.exceptions
        Internal Server Error = Exceptions.Internal Server Error ("Code Abort")
        bad_request_error = Exception.BadRequest("Code is broken")
        connection_error = connection_error("Code broke")
        client_error = Exception.ClientError("Invalid code")
        rate_limit_error = Exception.Forbidden(
            "Code is broken", error=[{"reason": "rateLimitExceeded"}]]
        )
        # add unavailable_error
        service_unavailable_error = Exception.ServiceUnavailable("Code is broken")

        self.assertTrue(_is_retryable(internal_server_error))
        self.assertTrue(_is_retryable(bad_request_error))
        self.assertTrue(_is_retryable(connection_error))
        self.assertFalse(_is_retryable(client_error))
        self.assertTrue(_is_retryable(rate_limit_error))
        # passed below assertion
        self.assertTrue(_is_retryable(service_unavailable_error))
```

https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/dbt/adapters/bigquery/connections.py#L57-L63

The ServiceUnavailable class inherits from the ServerError class, so it seems to pass the test.
I'd like to fix this, but is there anything else I look at?

**Comment by dbeatty10** [comment] 2023-12-18 15:01
Adding it to the [`test_is_retryable`](https://github.com/dbt-labs/dbt-bigquery/blob/06851679f75d18ece98c95d4eb2a0ddd16544f4d/tests/unit/test_bigquery_connection_manager.py#L81) test like that makes sense 👍

But ... the thing that is surprising to me: if [`ServiceUnavailable`](https://github.com/googleapis/python-api-core/blob/2a6a36bd820e1344c8b2526eb75d0b9f3a055d3b/google/api_core/exceptions.py#L409-L414) inherits from `ServerError` and your modified test passes, then why is this not being retried?

Is is possible that the BigQuery client is raising a different error class for 503 errors other than `ServiceUnavailable`?

@jx2lee Do you happen to have any python stacktraces available where you ran into this problem and dbt-bigquery didn't retry?

**Comment by jx2lee** [comment] 2023-12-20 12:19
@dbeatty10 Sorry for late!

> Is is possible that the BigQuery client is raising a different error class for 503 errors other than `ServiceUnavailable`?
> 
> @jx2lee Do you happen to have any python stacktraces available where you ran into this problem and dbt-bigquery didn't retry?

1. in [excepions.py](https://github.com/googleapis/python-api-core/blob/2a6a36bd820e1344c8b2526eb75d0b9f3a055d3b/google/api_core/exceptions.py), i didnt find 503 other than `ServiceUnavailable`. Can we get a more detailed log what was output when problem occurred 🧐? I'll try to find more exceptions that would be thrown by [Bigquery Client](https://github.com/googleapis/python-bigquery/blob/d225a94e718a85877c495fbd32eca607b8919ac6/google/cloud/bigquery/client.py#L180).
2. I'm not issue reporter, so I've never meet problem that got 503-error and didn't retry 😥. let me take a look at BigQueryClient code that if it's raising different error class.

**Comment by jx2lee** [comment] 2023-12-20 13:19
oh, i founded.

```python
    def test_is_retryable(self):
        _is_retryable = dbt.adapters.bigquery.connections._is_retryable
        exceptions = dbt.adapters.bigquery.impl.google.cloud.exceptions
        internal_server_error = exceptions.InternalServerError("code broke")
        bad_request_error = exceptions.BadRequest("code broke")
        connection_error = ConnectionError("code broke")
        client_error = exceptions.ClientError("bad code")
        rate_limit_error = exceptions.Forbidden(
            "code broke", errors=[{"reason": "rateLimitExceeded"}]
        )
        service_unvailable_error = exception_class_for_http_status(status_code=503)

        self.assertTrue(_is_retryable(internal_server_error))
        self.assertTrue(_is_retryable(bad_request_error))
        self.assertTrue(_is_retryable(connection_error))
        self.assertFalse(_is_retryable(client_error))
        self.assertTrue(_is_retryable(rate_limit_error))
        self.assertTrue(_is_retryable(service_unvailable_error))
```

when using `exception_class_for_http_status` function, above unit test failed.
![image](https://github.com/dbt-labs/dbt-bigquery/assets/63435794/53a91ad2-94a4-4d84-8af3-4d68d1c17446)

i found the cause(maybe), i'll fix our test code to pass and create PR.

**Comment by jx2lee** [comment] 2023-12-24 08:56
> Is is possible that the BigQuery client is raising a different error class for 503 errors other than ServiceUnavailable?

no, i expected `it's impossible.`
we can create error classes with the [from_http_status](https://github.com/googleapis/python-api-core/blob/17ff5f1d83a9a6f50a0226fb0e794634bd584f17/google/api_core/exceptions.py#L452) and [from_grpc_status](https://github.com/googleapis/python-api-core/blob/17ff5f1d83a9a6f50a0226fb0e794634bd584f17/google/api_core/exceptions.py#L532) functions. ([google.api_core.exceptions](https://github.com/googleapis/python-api-core/blob/main/google/api_core/exceptions.py)). error class generated from this functions always be "ServiceUnavailable"

> Do you happen to have any python stacktraces available where you ran into this problem and dbt-bigquery didn't retry?
That issue has never been reproduced...🙃 
I need to more detailed logs when it happened. 

If the issue reporter can't provide sufficient error logs, I think okay to close the issue.

- 503 code does not return any error class other than `ServiceUnavailable`
- The functions that raising error in the googleapis package only generate the `ServiceUnavailable`

**Comment by jx2lee** [comment] 2024-04-22 14:28
@dbeatty10 
Is there anything else should check?

**Comment by rrbarbosa** [comment] 2024-04-25 08:15
We did hit this recently. We use [external-tables](https://github.com/dbt-labs/dbt-external-tables) on a `on-run-start` macro. We also use service account impersonation in the dbt profile. While running dbt docs generate on CI environment we got:

```
('Unable to acquire impersonated credentials', '{\n  "error": {\n    "code": 503,\n    "message": "Authentication backend unavailable.",\n    "status": "UNAVAILABLE"\n  }\n}\n')
```

Because this happens intermittently on an isolated system, I don't have more logs.

**Comment by dbeatty10** [comment] 2024-04-30 22:18
Thanks for this report @rrbarbosa !

Since this is intermittent (and maybe relatively rare also), it has been hard to nail down.

If anyone can provide information to suggest that dbt is **not** retrying at least once, that would be very helpful 🙏

**Comment by dbeatty10** [comment] 2024-04-30 22:21
@jx2lee -- would you be willing to raise a PR with the addition you made to this test case?

I think that would be sufficient for us to establish that the `ServiceUnavailable` is retryable (which would allow us to close this issue).

**Comment by jx2lee** [comment] 2024-05-02 02:05
@dbeatty10 okay, i would create PR included above test code!

**Comment by jx2lee** [comment] 2024-05-04 16:26
@dbeatty10 
I created PR! Could you edit PR body or add comment to make it easier for reviewers to understand?

**Comment by mkielar** [comment] 2024-07-10 05:36
Got hit by this issue today, while generating "seed" tables with DBT running in CloudBuild:

```
"Step #7 - "dbt-seed": ('Unable to acquire impersonated credentials', '{\n  "error": {\n    "code": 503,\n    "message": "The service is currently unavailable.",\n    "status": "UNAVAILABLE"\n  }\n}\n')"
```

We're using impersonation with `dbt-bigquery` and it seems IAM was unavailable for a moment. We have no explicit retry configured, so - by the docs - it should retry once, but I see no such thing in the logs.

**Comment by mikealfare** [comment] 2024-10-24 20:51
GH closed this because an attached PR was merged. I think there is more to this, so I'm leaving it open.

**Closed** 2024-12-17 22:19 UTC
Labels: bug, good_first_issue, community
