### ISSUE TITLE
[CT-1072] Snapshot "Invalid empty identifier" error

### ISSUE THREAD

**Issue by brooks-j** [dbt-labs/dbt-bigquery#287] opened 2022-08-24 16:44 UTC
### Describe the bug

I'm trying to create a snapshot and I get this error from dbt:

Database Error in snapshot shipment_snapshot (snapshots/shipment_snapshot.sql)
  Syntax error: Invalid empty identifier at [5:34]

### Steps To Reproduce

Create a snapshot like this:

{% snapshot shipment_snapshot %}

    {{
        config(
          target_schema='sales_v2',
          strategy='timestamp',
          unique_key='id',
          updated_at='_fivetran_synced',
          invalidate_hard_deletes=True,
        )
    }}

    select * from {{ source('sales', 'shipment') }}
       
The one perhaps slightly odd thing about this is the target and the destination schemas are different.

The exact schema of the table probably doesn't matter as I tried it on 12 different tables.  

### Expected behavior

The snapshot worked the first time and populates data, but fails on all following attempts with the above error.  

### Screenshots and log output

I captured this SQL in Bigquery, which is obviously invalid and the source of the empty identifier error.  

drop view
     if exists `stage`.``.``stage`.`sales_v2`.`shipment_snapshot__dbt_tmp``

### System information
**The output of `dbt --version`:**

Running with dbt=1.1.0

**The operating system you're using:**

Linux-5.10.0-16-cloud-amd64-x86_64-with-glibc2.2.5

**The output of `python --version`:**

3.8.13

### Additional context
That is all.

**Comment by Fleid** [comment] 2022-08-31 23:31
Hi @brooks-j, thanks for the detailed info.
I wasn't able to reproduce the issue, with dbt-bigquery 1.1.0, core 1.1.2.

Can you please confirm I have the setup right:

On the BigQuery side:

- schema/dataset : `sales`
  -  table: `shipment`
- schema/dataset: `sales_v2`
  - table:  `shipment_snapshot`

On the dbt side:
- A source, `sales.shipment` - Would you mind sharing your source yml declaration by the way?
- A snapshot, `shipment_snapshot` reading from `source('sales','shipment')`

I have a project with just that, and no problem to dbt run, snapshot or build.

Looking at the logs, what's happening is dbt is generating a temporary view to refresh the snapshot, running a merge on that view, then removing the view. That temporary view is created on the destination schema (`sales_v2`) for you, so I'm not sure the `drop view` message you highlighted is relevant here.

**Comment by brooks-j** [comment] 2022-09-01 16:43
You need to run it twice.  The first time works, the second time doesn't.  Did you run the snapshot twice?  The drop view is relevant as this is the source of the "Invalid empty identifier" error and the drop view statement is obviously incorrect.  

stage..stage.sales_v2.shipment_snapshot__dbt_tmp 

This has five elements between the dots, and Bigquery (along with other DBs I know) only supports three.  Also note the "..", or empty identifier, which is exactly the error dbt is producing.  

The shipment_snapshot code can be found above.  

Here is the landing.yaml for the shipment table.

    - name: shipment
        columns:
          - name: id
          - name: _fivetran_synced
          - name: blood_glucose_check_frequency_c
          - name: blood_pressure_check_frequency_c
          - name: contact_c
          - name: created_by_id
          - name: created_date
          - name: enrollment_c
          - name: enrollment_document_set_c
          - name: follow_up_visit_c
          - name: follow_up_visit_other_c
          - name: is_closed_send_starter_kit_c
          - name: is_deleted
          - name: last_activity_date
          - name: last_modified_by_id
          - name: last_modified_date
          - name: name
          - name: onboarding_code_c
          - name: original_case_send_starter_kit_id_c
          - name: owner_id
          - name: patient_requires_bp_cuff_c
          - name: patient_requires_xl_bp_cuff_c
          - name: patient_requires_xl_scale_c
          - name: scale_id_c
          - name: shipping_city_c
          - name: shipping_postal_code_c
          - name: shipping_state_code_c
          - name: shipping_street_1_c
          - name: shipping_street_2_c
          - name: system_modstamp
          - name: tracking_number_shipping_c
          - name: unformatted_address_c

**Comment by Fleid** [comment] 2022-09-01 20:10
I'm wondering if this couldn't be a difference in version on dbt-bigquery and not core. My output of `dbt --version` looks like the following:
```BASH
Core:
  - installed: 1.1.2
  - latest:    1.2.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.1.0 - Update available!
```

On my side, here's the drop command that's get generated (`\logs\dbt.log\`), even if I run `dbt snapshot` 10 times:
```SQL
drop table if exists `dbt-project`.`dbt_dataset`.`snapshot_records__dbt_tmp`
```

**Comment by Fleid** [comment] 2022-09-01 20:17
Also, are you using [dbt-external-tables](https://github.com/dbt-labs/dbt-external-tables) here?

**Comment by brooks-j** [comment] 2022-09-02 20:46
In the our pipfile there this is set:  

dbt-bigquery = "~=1.1"

But in our requirements.txt for our tests we set this:

dbt-bigquery~=1.0.0

This is a bit odd.  I'll look into this further.

**Comment by Fleid** [comment] 2022-11-15 00:09
Hey @brooks-j, any update on that one?
I'll close it in the coming days if I don't hear back, you can always re-open later ;)

**Closed** 2022-12-07 23:14 UTC
Labels: bug, awaiting_response
