### ISSUE TITLE
[ADAP-918] [Bug] `latest` and `1.x.latest` tags for ghcr Docker releases are stale

### ISSUE THREAD

**Issue by AndreaGiardini** [dbt-labs/dbt-bigquery#941] opened 2023-09-25 14:31 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

If we look at the list of releases for Docker images on GitHub container registry ( https://github.com/dbt-labs/dbt-bigquery/pkgs/container/dbt-bigquery/versions?filters%5Bversion_type%5D=tagged ) we can see that not all of them have a `.latest` tag.

`1.0.latest` ✅
`1.1.latest` ✅
`1.2.latest` ✅
`1.3.latest` ✅
`1.4.latest` ❌
`1.5.latest` ❌
`1.6.latest` ❌

### Expected Behavior

I would expect all minor versions to have a `.latest` tag for consistency

### Steps To Reproduce

`docker pull ghcr.io/dbt-labs/dbt-bigquery:1.4.latest`

### Environment

```markdown
- OS:
- Python:
- dbt-core:
- dbt-bigquery:
```

**Comment by dbeatty10** [comment] 2023-09-25 15:59
Thanks for reporting this @AndreaGiardini 👍

Added your issue report to the listing here:
https://github.com/dbt-labs/dbt-core/issues/7571

The main explanation for the root cause is within https://github.com/dbt-labs/dbt-core/issues/7149

I'm not sure if we're intending to continue to officially support ghcr tags like `1.3.latest`, so will check with some folks internally and respond back here.

**Comment by dbeatty10** [comment] 2023-09-25 16:36
@AndreaGiardini after checking with some folks internally, we **do** intend to continue supporting [.latest](https://docs.getdbt.com/docs/core/docker-install#install-a-dbt-docker-image-from-github-packages) tags in ghcr images.

The ultimate solution will land when https://github.com/dbt-labs/dbt-core/issues/7149 is solved. We don't yet have an expected timeline for that work though.

**Comment by dbeatty10** [comment] 2024-01-31 21:04
https://github.com/dbt-labs/dbt-core/pull/9495 fixes the underlying issue (thank you @mikealfare !), and this particular issue will be resolved for each 1.x version of this adapter upon its next patch release.

We are choosing not to address any [un-supported versions](https://docs.getdbt.com/docs/dbt-versions/upgrade-core-in-cloud#latest-releases) at this time, so <=1.4.x will **not** be updated.

Here are the most recent ones for the supported versions of dbt-bigquery in [PyPI](https://pypi.org/project/dbt-bigquery/#history):
- 1.7.3
- 1.6.9
- 1.5.7

So this will be completely resolved for >=1.5.x when each of the following are released (but only if each is released prior to falling out of support):
- 1.7.4
- 1.6.10
- 1.5.8

**Comment by mikealfare** [comment] 2024-02-09 01:11
The updated process correctly tagged the Docker images that were recently [released](https://github.com/dbt-labs/dbt-bigquery/pkgs/container/dbt-bigquery/173951907?tag=latest). Closing this issue as a result.

**Closed by mikealfare** 2024-02-09 01:11 UTC
Labels: bug, support

**Comment by dbeatty10** [comment] 2024-02-09 01:26
Screenshot of `latest` and `1.7.latest`:

<img width="253" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/44704949/d1fdb5a2-c71a-4891-a336-68d5d06f0ed8">
