### ISSUE TITLE
[ADAP-503] [Regression] Persisted Metadata does not update on BigQuery tables

### ISSUE THREAD

**Issue by patricker** [dbt-labs/dbt-bigquery#687] opened 2023-04-28 17:12 UTC
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After upgrading to dbt 1.5.0 column metadata does not update in BigQuery and the model build shows as failed.

### Expected Behavior

metadata writes to the tables without issue in BigQuery.

### Steps To Reproduce

1. with dbt 1.5.0, writing to BigQuery
2. Update your dbt_project:
    +persist_docs:
      relation: true
      columns: true
3. Run a model with column level documentation
4. Error received after model is fully built, during the docs persist phase.

### Relevant log output

```shell
Error: google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/{table_path}?prettyPrint=false: Policy tags can only be attached to a leaf field.
```

### Environment

```markdown
- OS:debian
- Python:3.9.10
- dbt:1.5.0
```

### Which database adapter are you using with dbt?

bigquery

### Additional Context

I rolled back to 1.4.6 and the issue went away.

**Comment by dbeatty10** [comment] 2023-04-28 18:54
Thanks for reporting this @patricker and @steve-marmalade.

I was able to reproduce this when using [`policy_tags`](https://docs.getdbt.com/reference/resource-configs/bigquery-configs#policy-tags) and [`persist_docs`](https://docs.getdbt.com/reference/resource-configs/persist_docs).

**Comment by dbeatty10** [comment] 2023-04-28 18:57
### Simple reprex

`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle-bigquery"

models:
  my_dbt_project:
    +persist_docs:
      relation: true
      columns: true
```

`models/_models.yml`
```yaml
# version isn't required for dbt-core 1.5, but it is for 1.4
version: 2

models:
  - name: my_model
    columns:
      - name: id
        description: Primary key
        policy_tags:
          # Example pattern:
          # - 'projects/<gcp-project>/locations/<location>/taxonomies/<organization>/policyTags/<tag>'
          - projects/dbt-test-env/locations/us/taxonomies/5785568062805976401/policyTags/135489647357012267
```

`models/my_model.sql`
```sql
{{ config(materialized='table') }}

select 1 as id
```

**Comment by dgreen161** [comment] 2023-04-28 22:36
I've written a fix for this issue as above. It looks like this bug was introduced during this [MR](https://github.com/dbt-labs/dbt-bigquery/pull/542) which attempts to remove policy tags from all columns and structs on the model

**Comment by dbeatty10** [comment] 2023-04-28 23:54
Thanks for _truly_ reproducing this @dgreen161 🙏

Once I looked more closely at the error I "reproduced", it was actually a 403 rather than a 400 😅

**Closed** 2023-05-02 22:09 UTC
Labels: bug, regression

**Comment by dgreen161** [comment] 2023-05-16 20:56
Hi @nssalian @dbeatty10 Do you have a timeline for when this backport will be accessible through pip and dbt Cloud? It looks like 1.5.0 was last [released](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.5.0) 3 weeks ago. Thanks

**Comment by dgreen161** [comment] 2023-05-16 21:05
Hi @nssalian @dbeatty10 Do you have a timeline for when the backport will be accessible through pip and dbt Cloud? It looks like 1.5.0 was last [released](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.5.0) 3 weeks ago. I can see it's in the [beta release](https://github.com/dbt-labs/dbt-bigquery/releases/tag/v1.6.0b1) but that still leaves 1.5 with the issue. Thanks

**Comment by dbeatty10** [comment] 2023-05-19 13:59
@dgreen161 Thank you for checking-in!

We just released the backport [yesterday](https://pypi.org/project/dbt-bigquery/#history) -- wanna give it shot?

**Comment by dgreen161** [comment] 2023-05-19 16:24
@dbeatty10 Thanks for the update, I've just run the new version (v1.5.1) locally and the issue has now gone
