### ISSUE TITLE
[CT-2060] [Bug] Duplicate authorized views

### ISSUE THREAD

**Issue by jiwei-li** [dbt-labs/dbt-bigquery#522] opened 2023-02-08 03:07 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

After I upgraded dbt-bigquery to 1.4, it started to throw an error named `Duplicate authorized views`.

It worked fine prior dbt-bigquery 1.4.

In my config file, I have used `grant_access_to` to authorize views.

### Expected Behavior

It should not throw the error, even if the view is already authorized.

### Steps To Reproduce

1. add `grant_access_to` to a model (a view, that reads a table from a different dataset)
2. dbt run - it won't throw an error
3. dbt run - this time, it will throw the error

### Relevant log output

```shell
❯ dbt run --select vw_cordis_amm_history                                                                                          
02:57:29  Running with dbt=1.4.1
02:57:29  Unable to do partial parsing because a project config has changed
02:57:31  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 3 unused configuration paths:
- models.cerebro_dbt.l1-common
- models.cerebro_dbt.l1-regulatory.tables
- models.cerebro_dbt.l1-monitoring.tables
02:57:31  Found 129 models, 47 tests, 0 snapshots, 0 analyses, 361 macros, 1 operation, 5 seed files, 44 sources, 0 exposures, 0 metrics
02:57:31  
02:57:34  
02:57:34  Running 1 on-run-start hook
02:57:34  1 of 1 START hook: cerebro_dbt.on-run-start.0 .................................. [RUN]
02:57:35  1 of 1 OK hook: cerebro_dbt.on-run-start.0 ..................................... [None (0 processed) in 0.55s]
02:57:35  
02:57:35  Concurrency: 1 threads (target='dev')
02:57:35  
02:57:35  1 of 1 START sql view model b1x_ha_jiwei_cerebro_l1.vw_cordis_amm_history ...... [RUN]
02:57:36  Unhandled error while executing /Users/jiwei.li/Projects/b1x-airflow/cerebro-dbt/target/run/cerebro_dbt/models/l1/views/vw_cordis_amm_history.sql
400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/atoms-b1fs-dev-5320/datasets/b1x_ha_dev_cerebro_l0?prettyPrint=false: Duplicate authorized views
02:57:36  1 of 1 ERROR creating sql view model b1x_ha_jiwei_cerebro_l1.vw_cordis_amm_history  [ERROR in 1.07s]
02:57:36  
02:57:36  Finished running 1 view model, 1 hook in 0 hours 0 minutes and 4.59 seconds (4.59s).
02:57:36  
02:57:36  Completed with 1 error and 0 warnings:
02:57:36  
02:57:36  400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/atoms-b1fs-dev-5320/datasets/b1x_ha_dev_cerebro_l0?prettyPrint=false: Duplicate authorized views
02:57:36  
02:57:36  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Environment

```markdown
- OS: MacOS 13.2
- Python: Python 3.8.13
- dbt-core: 1.4.1
- dbt-bigquery: 1.4.0
```

**Comment by Fleid** [comment] 2023-02-10 22:51
I can reproduce, bumping as `regression`

**Comment by Fleid** [comment] 2023-03-24 22:57
Following the patch, I can't reproduce in 1.4.2! Closing :)

**Closed by Fleid** 2023-03-24 22:57 UTC
Labels: bug, regression
