### ISSUE TITLE
[CT-881] refactor retries

### ISSUE THREAD

**Issue by nathaniel-may** [dbt-labs/dbt-bigquery#231] opened 2022-07-21 17:25 UTC
We currently have a non-trivial amount of code to support our homegrown retry strategy via `_retry_and_handle`. This in inferior to using Google's provided and configurable `Retry()` decorator.

This is an extension to the work started in #230.

Goals:
- Make sure all network calls have the `Retry()` decorator.
- If the user provides configuration for the job_* retry/timeout options, plumb them into the Retry() decorator in the appropriate ways.
- Delete homegrown retry code

Context:
It is reasonable that a user would want a very quick timeout if a job fails to create/submit, and a much much _much_ longer timeout for a job that's actually running (e.g. models that take >1 hr to run).

**Comment by ChenyuLInx** [comment] 2022-07-27 22:40
I think we are leaving the adding retry/timeout for dataproc out of the initial beta PR, @nathaniel-may  can you talk a look when your change goes in and see if we can just reuse the decorator there? Otherwise we can create an issue to track the work for dataproc separately

**Comment by hui-zheng** [comment] 2022-08-30 01:05
I agree/like this approach. it's much cleaner and leverage the more robust Google Retry mechanism.

One thing to call out.
Dbt currently has two ways to config bq job retry: `job_retry_deadline_seconds` and `job_retries`. 

However, [Google Retry](https://googleapis.dev/python/google-api-core/latest/retry.html#google.api_core.retry.Retry) only uses `job_retry_deadline_seconds`, to control retries, not `job_retries`. 

when moving over to Google Retry, I suggest 
 - removing `job_retries` config
 - expand `job_retry_deadline_seconds` into two configs: `job_creation_retry_deadline_seconds` and `job_execution_retry_deadline_seconds`
this provide the proper control over retries in both `job_creation` and `job_execution` steps.

**Comment by lostmygithubaccount** [comment] 2022-09-22 21:11
I believe this directly relates, reported by a user: https://github.com/dbt-labs/dbt-bigquery/issues/274

to summarize, dbt is cancelling its run but not the actual BigQuery job in the backend. they and I would expect if the timeout is reached for the job to be cancelled instead of silently continuing to run

I'm assuming that could be addressed in this refactor when picked up?

**Comment by jeremyyeo** [comment] 2023-08-25 03:52
Adding this here for future reference.

Currently, the [dbt-bigquery configuration](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#timeouts-and-retries) of `job_execution_timeout_seconds` is being applied to the `QueryJob` `result` method's `timeout` param:

https://github.com/dbt-labs/dbt-bigquery/blob/d7fb235a42780841c82ea5b01a647b3416070afe/dbt/adapters/bigquery/connections.py#L719

The `timeout` param is [actually](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.QueryJob#google_cloud_bigquery_job_QueryJob_result):

> The number of seconds to wait for the underlying HTTP transport before using retry. If multiple requests are made under the hood, timeout applies to each individual request.

It is not, as perhaps one would expect it to be, a "cancel a BigQuery job if it has been running for more than [timeout]" config - but more so "how long should the client wait for a response from BQ when the SQL operation is kicked off" config.

In fact, there is a related issue in the python bigquery repo itself https://github.com/googleapis/python-bigquery/issues/1421 - which is essentially asking to expose the query_job_timeout_ms config - which **would be** "cancel a BigQuery job if it has been running for more than [timeout]".

Because that config is not yet available, from a dbt-bigquery perspective, to implement "cancel a BigQuery job if it has been running for more than [timeout]" - I think we need to call [`QueryJob` `cancel`](https://cloud.google.com/python/docs/reference/bigquery/latest/google.cloud.bigquery.job.QueryJob#google_cloud_bigquery_job_QueryJob_cancel) most likely - in the place where we poll upon reaching timeout:

https://github.com/dbt-labs/dbt-bigquery/blob/d7fb235a42780841c82ea5b01a647b3416070afe/dbt/adapters/bigquery/impl.py#L559-L572

----

Now, interestingly, one can [set default values for a BQ project](https://cloud.google.com/bigquery/docs/default-configuration), like so:

```sql
alter project `cse-sandbox-319708` set options (`region-us.default_query_job_timeout_ms` = 300000);
```

> The minimum default_query_job_timeout_ms is 5 minutes / 30000 ms.

Now, by setting that, there are yet interesting observations.

### Running a job that's > 5 minutes from the BigQuery UI.

![image](https://github.com/dbt-labs/dbt-bigquery/assets/8496748/42cfee95-297e-4987-b00d-fff965c95011)

The expected behaviour is observed, and a BQ job that took over 5 minutes was terminated with "Job execution was cancelled: Job timed out after 5 min 0 sec".

### Running a job that's > 5 minutes using Google's BigQuery Python library directly.

```python
from google.cloud import bigquery

client = bigquery.Client()

# Perform a query.
query = """
call dbt_jyeo.fake_sleep(400);
select 1 id;
"""

query_job = client.query(query)  # API request
rows = query_job.result()  # Waits for query to finish

for row in rows:
    print(row)
```

![image](https://github.com/dbt-labs/dbt-bigquery/assets/8496748/afa7f2f4-e5a8-4c4d-bdc3-a6339470715a)

### Running a job that's > 5 minutes using Google's BigQuery Python library directly + setting `timeout`.

And for completeness, if we used some sort of `timeout` in the `result()` method as well:

```python
from google.cloud import bigquery

client = bigquery.Client()

# Perform a query.
query = """
call dbt_jyeo.fake_sleep(400);
select 1 id;
"""

query_job = client.query(query)  # API request
rows = query_job.result(timeout=60)  # Waits for query to finish

for row in rows:
    print(row)
```

<img width="1644" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/8496748/1dfb3980-36a7-4baf-ab57-474c9993428e">

^ On the client side, we did run into an Exception - however, in BQ, the job still ran to completion (taking > 5 minutes). This is the exact behaviour we see in dbt-biqquery.

----

Effectively, as of now, there is no apparent way for a user of dbt-bigquery to set up "cancel a BigQuery job if it has been running for more than [timeout]" - because, as above, we've shown that even by setting a default on the BQ side, the python bigquery library bypasses that anywya.

**Closed** 2023-09-11 18:12 UTC
Labels: enhancement, tech_debt
