### ISSUE TITLE
[ADAP-1029] [Bug] Materialized view does not update when query is changed

### ISSUE THREAD

**Issue by bnaul** [dbt-labs/dbt-bigquery#1021] opened 2023-11-12 13:42 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

For a `view`, changing the query causes the view to be recreated. For a materialized view, nothing happens.

### Expected Behavior

Materialized view should also get updated like a view does.

### Steps To Reproduce

```
# Create initial views
==> models/example/mview.sql <==
{{ config(materialized='materialized_view') }}

SELECT * FROM jaffle_shop.my_first_dbt_model
WHERE id >= 100

==> models/example/view.sql <==
{{ config(materialized='view') }}

SELECT * FROM jaffle_shop.my_first_dbt_model
WHERE id >= 100

(.venv) ➜  mview git:(dbt) ✗ dbt run
13:35:55  Running with dbt=1.8.0-a1
13:35:56  Registered adapter: bigquery=1.8.0-a1
13:35:56  Found 2 models, 0 sources, 0 exposures, 0 metrics, 449 macros, 0 groups, 0 semantic models
13:35:56
13:35:57  Concurrency: 2 threads (target='dev')
13:35:57
13:35:57  1 of 2 START sql materialized_view model jaffle_shop.mview ..................... [RUN]
13:35:57  2 of 2 START sql view model jaffle_shop.view ................................... [RUN]
13:35:58  2 of 2 OK created sql view model jaffle_shop.view .............................. [CREATE VIEW (0 processed) in 0.79s]
13:36:02  1 of 2 OK created sql materialized_view model jaffle_shop.mview ................ [SCRIPT (0 processed) in 4.56s]
13:36:02
13:36:02  Finished running 1 view model, 1 materialized_view model in 0 hours 0 minutes and 5.67 seconds (5.67s).

# Change query definition in both views
# New queries:
==> models/example/mview.sql <==
{{ config(materialized='materialized_view') }}

SELECT * FROM jaffle_shop.my_first_dbt_model
WHERE id < 50

==> models/example/view.sql <==
{{ config(materialized='view') }}

SELECT * FROM jaffle_shop.my_first_dbt_model
WHERE id < 50

# Re-run
(.venv) ➜  mview git:(dbt) ✗ dbt run
13:40:05  Running with dbt=1.8.0-a1
13:40:06  Registered adapter: bigquery=1.8.0-a1
13:40:06  Found 2 models, 0 sources, 0 exposures, 0 metrics, 449 macros, 0 groups, 0 semantic models
13:40:06
13:40:07  Concurrency: 2 threads (target='dev')
13:40:07
13:40:07  1 of 2 START sql materialized_view model jaffle_shop.mview ..................... [RUN]
13:40:07  2 of 2 START sql view model jaffle_shop.view ................................... [RUN]
13:40:08  2 of 2 OK created sql view model jaffle_shop.view .............................. [CREATE VIEW (0 processed) in 0.96s]
13:40:11  1 of 2 OK created sql materialized_view model jaffle_shop.mview ................ [SCRIPT (0 processed) in 4.11s]
13:40:11
13:40:11  Finished running 1 view model, 1 materialized_view model in 0 hours 0 minutes and 5.16 seconds (5.16s).

# View query updates, but not materialized view
(.venv) ➜  mview git:(dbt) ✗ bq show --format json jaffle_shop.view | jq '.view.query'
"SELECT * FROM jaffle_shop.my_first_dbt_model\nWHERE id < 50"

(.venv) ➜  mview git:(dbt) ✗ bq show --format json jaffle_shop.mview | jq '.materializedView.query'
"SELECT * FROM jaffle_shop.my_first_dbt_model\nWHERE id >= 100"
```

### Environment

```markdown
- OS: MacOS 13.2
- Python: 3.10.13
- dbt-core: `main` (`e24f9b3da722328e24ee10a06fa2e8d2ca73b3e6`)
- dbt-bigquery: `main` (`9e39acfc1207f3e8495b81b675b7be99d0668587`)
```

**Comment by dbeatty10** [comment] 2023-11-13 19:03
Thanks for opening this @bnaul !

I'm going to close this as a duplicate of #8862 because it looks the same. But if it looks like a unique issue to you, just let me know and we can reconsider re-opening this.

In particular, see @Fleid's comment here: https://github.com/dbt-labs/dbt-core/issues/8862#issuecomment-1779693926

**Closed by dbeatty10** 2023-11-13 19:03 UTC
Labels: bug, triage, materialized_views

**Comment by bnaul** [comment] 2023-11-13 19:06
Thanks @dbeatty10, I had missed this since I was only searching `dbt-bigquery`
