### ISSUE TITLE
[CT-2119] [Bug] Bigquery does not prunes partitions in incremental model after update dbt to v1.4 

### ISSUE THREAD

**Issue by igeush** [dbt-labs/dbt-bigquery#536] opened 2023-02-14 17:29 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

In 1.4 version when using` incremental_strategy: insert_overwrite` and `data_type: timestamp` dbt wrap the partitioning column by **timestamp()**.

```
when not matched by source
    and timestamp(timestamp_trunc(DBT_INTERNAL_DEST.date_ts, month)) in unnest(dbt_partitions_for_replacement) 
    then delete
```

Due to this Bigquery does not prunes partitions. What increases the cost of SQL execution.

### Expected Behavior

Do not wrap partitioning column.

### Steps To Reproduce

```
{{
    config(
        schema='datamart',
        materialized='incremental',
        incremental_strategy = 'insert_overwrite',
        partition_by = {'field': 'date_ts',
                        'data_type': 'timestamp',
                        'granularity': 'month'},
        enabled=true
    )
}}

select 
  case_number
, date as date_ts
from  `bigquery-public-data.chicago_crime.crime`
{%- if is_incremental() -%}
where date between timestamp('2023-02-04') and timestamp('2023-02-05')
{%- endif %}
```

or compare

```
SELECT * FROM `any-big-table-partition-by-date_ts`
WHERE timestamp(TIMESTAMP_TRUNC(date_ts, day)) = timestamp('2023-01-01 00:00:00');
```
with
```
SELECT * FROM `any-big-table-partition-by-date_ts`
WHERE TIMESTAMP_TRUNC(date_ts, day) = timestamp('2023-01-01 00:00:00')
```
with wrap:

![ex-1](https://user-images.githubusercontent.com/8916217/218810872-1bcafa4c-5a02-49a7-bca4-092a8b7c6124.png)
without wrap:

![ex-2](https://user-images.githubusercontent.com/8916217/218810877-71e03e2d-2801-4684-a2ae-37194443430d.png)

### Environment

```markdown
- dbt-bigquery: 1.4.1
```

**Comment by Fleid** [comment] 2023-02-14 22:51
@igeush I feel like this is a duplicate of #483 - could you please confirm?
There is a workaround over there if that's the case:

Use `"copy_partitions": true` setting such as

```YAML
 partition_by = {
          "field": "hour",
          "data_type": "timestamp",
          "granularity": "hour",
          "copy_partitions": true
        }
```

**Comment by Fleid** [comment] 2023-02-15 16:25
So let's this keep this one open. I linked the PR resolving the other one, and hopefully it will resolve this one too.

**Comment by Kayrnt** [comment] 2023-02-16 00:06
It's the same issue, since BQ can't figure out in its query plan that a TIMESTAMP cast of TIMESTAMP is a no op then, it's doing a table full scan... it will be fixed through https://github.com/dbt-labs/dbt-bigquery/pull/485

**Closed** 2023-03-02 21:43 UTC
Labels: bug
