### ISSUE TITLE
[CT-606] `dbt-bigquery` incompatible with Apache Airflow 2.3.0

### ISSUE THREAD

**Issue by aspain** [dbt-labs/dbt-bigquery#181] opened 2022-05-04 19:30 UTC
### Describe the bug
A clear and concise description of what the bug is. What command did you run? What happened?
Attempting to install `dbt-bigquery` via `requirements.txt` in an Airflow project 

```
ERROR: Cannot install apache-airflow, apache-airflow==2.3.0+astro.1 and dbt-bigquery because these package versions have conflicting dependencies.
```

apache-airflow 2.3.0 depends on jsonschema<5.0 and >=3.2.0 
while dbt-core 0.13.0 depends on jsonschema==2.6.0

### Steps To Reproduce
In as much detail as possible, please provide steps to reproduce the issue. Sample data that triggers the issue, example model code, etc is all very helpful here.

Attempting to start an Astronomer Airflow project using requirements.txt with contents of:

```
airflow-dbt
dbt-bigquery
```

When attempting to only install `airflow-dbt` without `dbt-bigquery`, the image builds as expected

### Expected behavior
Install packages and build image

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

```
 > [5/1] RUN if grep -Eqx 'apache-airflow\s*[=~>]{1,2}.*' requirements.txt; then     echo >&2 "Do not upgrade by specifying 'apache-airflow' in your requirements.txt, change the base image instead!";  exit 1;   fi;   pip install --no-cache-dir -q -r requirements.txt:                                                                                                                                               
#9 0.684 + grep -Eqx 'apache-airflow\s*[=~>]{1,2}.*' requirements.txt                                                                                                                                        
#9 0.690 + pip install --no-cache-dir -q -r requirements.txt                                                                                                                                                 
#9 276.3 ERROR: Cannot install apache-airflow, apache-airflow==2.3.0+astro.1 and dbt-bigquery because these package versions have conflicting dependencies.                                                  
#9 276.3 ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
#9 276.7 WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
#9 276.7 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

```
ERROR: Cannot install apache-airflow, apache-airflow==2.3.0+astro.1 and dbt-bigquery because these package versions have conflicting dependencies.
The conflict is caused by:
  apache-airflow 2.3.0+astro.1 depends on jsonschema<5.0 and >=3.2.0
  flask-appbuilder 3.4.5 depends on jsonschema<5 and >=3
  dbt-core 0.13.0 depends on jsonschema==2.6.0
```
### System information
**The operating system you're using:**
MacOS 11.5.2 

**The output of `python --version`:**
Python 3.9.7

**Comment by jtcohen6** [comment] 2022-05-05 13:24
@aspain Thanks for opening, and sorry about the delay here on our end. The `jsonschema<3.2` upper bound is coming from `hologram`, a dependency of `dbt-core`. That's being tracked in this issue: https://github.com/dbt-labs/hologram/issues/43

We're aware of the dependency conflict with Airflow. We'll need to resolve it by releasing a new version of `hologram`, and updating the dependency in `dbt-core`.

(I'm not sure why it's trying to install `dbt-core==0.13.0` above, rather than latest `dbt-bigquery==1.1.0 dbt-core==1.1.0`)

For now, I'm going to close this as a duplicate of the work being tracked in the issue linked above

**Closed by jtcohen6** 2022-05-05 13:24 UTC
Labels: bug, duplicate
