### ISSUE TITLE
[CT-1107] Log output for materialization incremental incorrectly reports bytes processed

### ISSUE THREAD

**Issue by benney-au-le** [dbt-labs/dbt-bigquery#293] opened 2022-08-30 23:58 UTC
### Describe the bug
When you run an incremental model, two bigquery jobs are created:
1. create_table_as_select job
2. merge job

The log output only shows bytes processed / row processed for the merge job, but it should show both compiled.

### Steps To Reproduce
1. Create an incremental model.
2. Set the config of the incremental model to the above
```
{{
    config(
        materialized='incremental',
        on_schema_change='append_new_columns',
        partition_by = {
          "field": "p_date",
          "data_type": "date",
          "granularity": "day"
        },
    )
}}
```
3. Inside the incremental model, perform a full table scan of the upstream table.
4. Querying the information schema, to see the jobs generated.

```sql
select 
total_slot_ms / TIMESTAMP_DIFF(end_time, start_time, MILLISECOND) as avg_slot_usage
, *
FROM `region-us`.INFORMATION_SCHEMA.JOBS_BY_PROJECT
where creation_time > timestamp_sub(current_timestamp(), interval 1 hour)
and statement_type != "SCRIPT"
order by creation_time desc
```

### Expected behavior
If an incremental model requires two jobs to complete it, the dbt log output should show both jobs or combine the bytes processed metrics from both.

### Screenshots and log output
I ran the incremental model, the incremental model requires two jobs:
1. create_table_as_select job -- processed 600 GB
2. merge job -- processed 0 bytes

The output hides metrics for job 1 which was an expensive mistake in this case!
```
06:43:32  1 of 1 START incremental model reporting_sl.mobile_metrics_daily ............... [RUN]
06:43:41  1 of 1 OK created incremental model reporting_sl.mobile_metrics_daily .......... [MERGE (0.0 rows, 0 processed) in 8.91s]
```

### System information
**The output of `dbt --version`:**
```
Core:
  - installed: 1.1.2
  - latest:    1.2.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.1.0 - Update available!
```

**The operating system you're using:**
linux

**The output of `python --version`:**
Python 3.9.13

**Comment by Fleid** [comment] 2022-09-01 20:33
Hey @benney-au-le, could you please share the dbt command you're using to trigger both a `CREATE TABLE` and a `MERGE` on the same run? I can't reproduce the behavior yet.

I'm running the same version as you, my incremental view is defined as:

```
{{
    config(
        materialized='incremental',
        on_schema_change='append_new_columns'
    )
}}


select
    *
from {{ref('newish_records')}}

{% if is_incremental() %}

  -- this filter will only be applied on an incremental run
  where updated_at > (select max(updated_at) from {{ this }})

{% endif %}

```

And I get:
- `CREATE` on `dbt run --full_refresh --select incremental_records`
- `MERGE` on `dbt run  --select incremental_records`

I'm wondering what I'm missing. Thanks!

**Comment by Fleid** [comment] 2022-09-01 20:36
Scrapping my previous comment, got it, looking into it ;)

**Comment by Fleid** [comment] 2022-09-01 20:40
@jtcohen6 sorry to pull you in, but I'm wondering if this isn't a core behavior rather than one specific to the BQ adapter? The fact that an incremental refresh only log metrics from the _final merge_ and not the initial _create temporary table_.

**Comment by jtcohen6** [comment] 2022-09-01 22:37
@Fleid Correct! This is a known fact in `dbt-core`, that only the `"main"` statement in a multi-step materialization is used to report the "result" from that materialization (e.g. displayed on stdout, and in `run_results.json`).

We _do_ capture `bytes_processed`, and other query-specific metadata, for every query that dbt executes. It would be possible to include this information in our structured logs. This issue provides an overview of the proposal: https://github.com/dbt-labs/dbt-core/issues/5325

As a longer-term initiative, we are looking to make our logs the source of truth for all dbt metadata. For now, we should chalk this issue up as a known limitation of `dbt-core`, and one that's unlikely to change without a significant overhaul of our materializations.

**Comment by Fleid** [comment] 2022-09-06 23:48
@benney-au-le I'm closing this issue following the comment above - this is a limitation of `dbt-core`, that should be addressed but not in the short term. Please re-open if you think there's more to it.

**Closed by Fleid** 2022-09-06 23:48 UTC
Labels: bug, awaiting_response
