### ISSUE TITLE
[ADAP-1060] Crash when running model in GCP with docker image ghcr.io/dbt-labs/dbt-bigquery:latest

### ISSUE THREAD

**Issue by aleloi** [dbt-labs/dbt-bigquery#1043] opened 2023-12-06 08:20 UTC
Hi, I just got the problem first mentioned in (closed as fixed) https://github.com/dbt-labs/dbt-bigquery/issues/531 when running with the latest docker image. I've commented in https://github.com/dbt-labs/dbt-bigquery/issues/531#issuecomment-1842391982, but couldn't reopen it. My dockerfile is:

```Dockerfile
FROM ghcr.io/dbt-labs/dbt-bigquery:latest # downgrading to 1.6.6 fixes the issue
WORKDIR /usr/src/app
COPY . .
ENV PROJECT_ID=<my-project-id>
CMD ["run", "--profiles-dir", "dbt_profile_dir", "--project-dir", "<my-project-dir>/"]
```

My dbt profile is
```yaml
<my-project-name>:
  target: prod
  outputs:
    prod:
      dataset: <my-dataset>
      job_execution_timeout_seconds: 600
      job_retries: 1
      location: europe-west1
      method: oauth
      priority: interactive
      project: "{{ env_var('PROJECT_ID', '') }}"
      threads: 1
      type: bigquery
      gcs_bucket: <my-gcs-bucket>
      dataproc_region: europe-west1
```

With this setup, pyspark crashes when running a 'dbt.ref'. The JVM stack trace looks like the one above in https://github.com/dbt-labs/dbt-bigquery/issues/531#issuecomment-1428994813 
```python
Using the default container image
Waiting for container log creation
PYSPARK_PYTHON=/opt/dataproc/conda/bin/python
Generating /home/spark/.pip/pip.conf
Configuring index-url as 
Configuring target as /mnt/dataproc/python/site-packages
JAVA_HOME=/usr/lib/jvm/temurin-17-jdk-amd64
SPARK_EXTRA_CLASSPATH=
:: loading settings :: file = /etc/spark/conf/ivysettings.xml
Initialized pyspark model calculation
Traceback (most recent call last):
  File "/var/dataproc/tmp/srvls-batch-28872ee4-d955-4ff0-bc8d-8361c1a46df0/my_model.py", line 249, in <module>
    df = model(dbt, spark)
  File "/var/dataproc/tmp/srvls-batch-28872ee4-d955-4ff0-bc8d-8361c1a46df0/my_model.py", line 56, in model
    df_pyspark = dbt.ref("my_table")
  File "/var/dataproc/tmp/srvls-batch-28872ee4-d955-4ff0-bc8d-8361c1a46df0/my_model.py", line 239, in <lambda>
    self.ref = lambda *args: ref(*args, dbt_load_df_function=load_df_function)
  File "/var/dataproc/tmp/srvls-batch-28872ee4-d955-4ff0-bc8d-8361c1a46df0/my_model.py", line 207, in ref
    return dbt_load_df_function(refs[key])
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 177, in load
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/java_gateway.py", line 1321, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 190, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.9.5-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o75.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: com.google.cloud.spark.bigquery.BigQueryRelationProvider Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at scala.collection.convert.JavaCollectionWrappers$JIteratorWrapper.hasNext(JavaCollectionWrappers.scala:37)
	at scala.collection.StrictOptimizedIterableOps.filterImpl(StrictOptimizedIterableOps.scala:225)
	at scala.collection.StrictOptimizedIterableOps.filterImpl$(StrictOptimizedIterableOps.scala:222)
	at scala.collection.convert.JavaCollectionWrappers$JIterableWrapper.filterImpl(JavaCollectionWrappers.scala:58)
	at scala.collection.StrictOptimizedIterableOps.filter(StrictOptimizedIterableOps.scala:218)
	at scala.collection.StrictOptimizedIterableOps.filter$(StrictOptimizedIterableOps.scala:218)
	at scala.collection.convert.JavaCollectionWrappers$JIterableWrapper.filter(JavaCollectionWrappers.scala:58)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:657)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:725)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:207)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NoClassDefFoundError: scala/Serializable
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 27 more
Caused by: java.lang.ClassNotFoundException: scala.Serializable
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 45 more
```

_Originally posted by @aleloi in https://github.com/dbt-labs/dbt-bigquery/issues/531#issuecomment-1842391982_

**Comment by nathaniel-may** [comment] 2023-12-06 18:34
notes for triage: attempt to recreate python model bug separately from docker image as well.

**Comment by dbeatty10** [comment] 2023-12-11 00:45
Thanks for including this piece @aleloi:
```
FROM ghcr.io/dbt-labs/dbt-bigquery:latest # downgrading to 1.6.6 fixes the issue
```

### Root cause

The root cause is that the `latest` tag is not up-to-date [here](https://github.com/dbt-labs/dbt-bigquery/pkgs/container/dbt-bigquery/versions?filters%5Bversion_type%5D=tagged) and is pointing to 1.3.0 instead of 1.7.2:

<img width="268" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/44704949/78139f34-7677-49d3-aa89-87b273a763df">

<br />
<img width="261" alt="image" src="https://github.com/dbt-labs/dbt-bigquery/assets/44704949/a559e050-ba60-4e4c-a723-a0fe3d8a02d2">

### Workaround

In the meantime, the workaround is to pin to a specific version like this, which it sounds like you figured out:
```
FROM ghcr.io/dbt-labs/dbt-bigquery:1.6.6
```

### Summary

This specific issue is already covered by https://github.com/dbt-labs/dbt-bigquery/issues/941, so I'm going to close this as a duplicate.

The problem you experienced will be resolved along with that issue.

**Closed by dbeatty10** 2023-12-11 00:45 UTC
Labels: bug, triage
