### ISSUE TITLE
[CT-1316] [Bug] Error parsing metadata in python-bigquery

### ISSUE THREAD

**Issue by kyleabeauchamp** [dbt-labs/dbt-bigquery#342] opened 2022-10-07 21:34 UTC
### Is this a new bug in dbt-bigquery?

- [X] I believe this is a new bug in dbt-bigquery
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I'm trying to get python running with  1.3.0rc3 and am hitting an error.  There is very likely user error here, but the fact that my error message is so cryptic might also be considered a bug 😂 .

```
import pandas as pd


def model(dbt, session):
    dbt.config(materialized="table")

    x = pd.DataFrame(dict(A=[1, 2, 3], B=list("pqr")))
    return x

dbt run --models models/python_test/
hpack_parser.cc:1227]         Error parsing metadata: error=invalid value key=content-type value=text/html; charset=UTF-8
21:27:24  Unhandled error while executing model.my_project.test
501 Received http2 header with status: 404
21:27:24  1 of 1 ERROR creating python table model my_project.test ....... [ERROR in 0.85s]
21:27:24  
21:27:24  Finished running 1 table model in 0 hours 0 minutes and 2.88 seconds (2.88s).
21:27:24  
21:27:24  Completed with 1 error and 0 warnings:
21:27:24  
21:27:24  501 Received http2 header with status: 404
21:27:24  
21:27:24  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

### Expected Behavior

Either my model works or raises a more interpretable error.

### Steps To Reproduce

See above

### Environment

```markdown
- OS:OSX
- Python: 3.8
- dbt-core:1.3.0.rc2
- dbt-bigquery:1.3.0.rc3
```

**Comment by lostmygithubaccount** [comment] 2022-10-07 23:38
hi @kyleabeauchamp, I'm not able to reproduce this with the same RC versions installed. is this 100% reproducible for you? my best guess is that errors is being returned by the GCP services in the backend and might be something transient 

have you also followed the [instructions in the BigQuery tab for Python models in docs](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/python-models#specific-data-platforms)?

**Comment by kyleabeauchamp** [comment] 2022-10-08 02:44
Thanks, I have modeled my configs based on the BigQuery tab on that doc page.  My naive guess is that I'm missing some permissions and that the root cause is not being printed.  I'll do some manual investigations about my permissions to confirm.

**Comment by jtcohen6** [comment] 2022-10-18 11:49
I think I remember seeing an error a lot like this when I mistyped the `dataproc_region` (`us-central-1` instead of `us-central1`)

**Comment by kyleabeauchamp** [comment] 2022-10-18 16:41
That sounds very plausible!  Thank you.

**Comment by kyleabeauchamp** [comment] 2022-10-20 22:07
That did it, I'm not hitting a different error so it was a misnamed region string.   I'm happy to either close this or keep it open if there's a desire for error message clarity.

**Comment by lostmygithubaccount** [comment] 2022-10-23 15:19
thanks @jtcohen6! glad that worked for you @kyleabeauchamp. I'm going to go ahead and close this one out with the rationale that we have a lot of work to do improving error messages (either in general, or certainly for the new Python models) so we'll open up some high-level tracking work for those items in the near future. I'll keep this one in mind and try to reference it there

thanks for trying out the new stuff!

**Closed by lostmygithubaccount** 2022-10-23 15:19 UTC
Labels: bug, awaiting_response, Refinement
