### ISSUE TITLE
[CT-1060] Job continues to run after timeout is reached

### ISSUE THREAD

**Issue by atrbgithub** [dbt-labs/dbt-bigquery#274] opened 2022-08-19 10:20 UTC
### Describe the bug
Now that `timeout_seconds` is actually used now rather than being ignored (which I believe is aliased to `job_execution_timeout_seconds`), we started to see a number of jobs hit the timeout we had configured in our dbt profile. 

When a timeout is reached we see the following error:
```
 Operation did not complete within the designated timeout
```

We execute our tasks by airflow, airflow sees this as a failure and retries the job. 

However, when checking in BigQuery there are now two jobs running, the original job is not cancelled, it appears to continue to run. Is this expected behaviour?

Does dbt send a request to BigQuery to cancel the job which hit dbt's timeout? Does google does ignore the request and continue to run the job until completion?

The eventual result with a task which had 2 retries in Airflow was 2 failed Airflow runs (as they both hit the timeout set in dbt) and two completed jobs in Bigquery which were marked as successful. 

### Steps To Reproduce
Set a timeout for a dbt task which is shorter than the actual runtime. It will hit the timeout but will not be cancelled.

### Expected behavior
Dbt should hit the timeout and request that the job be cancelled via the BigQuery api. 

### Screenshots and log output
n/a

### System information
**The output of `dbt --version`:**
```
dbt --version
Core:
  - installed: 1.2.0
  - latest:    1.2.0 - Up to date!

Plugins:
  - bigquery: 1.2.0 - Up to date!
```

**The operating system you're using:**
RHEL 8 compatible

**The output of `python --version`:**
```
python --version
Python 3.8.12
```
### Additional context
n/a

**Comment by lostmygithubaccount** [comment] 2022-09-20 15:35
hi @atrbgithub, apologies for the delay on this one. I'm unable to reproduce this. capturing what I've done, first adding the job timeout in `~/.dbt/profiles.yml`:

```yaml
bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      schema: dbt_cody
      threads: 8
      project: dbt-test-env
      # triaging
      job_execution_timeout_seconds: 1
```

artifically create a model (I used `gh clone dbt-labs/jaffle_shop`, then added `models/test.sql`):

```sql
{# interestingly here, 1000 hits the query plan too complex issue #}
{% set num_loops = 400 %}

with orders as (

    select * from {{ ref('orders') }}

),

final as (
    {# jinja for loop unioning all the orders #}
    {%- for i in range(num_loops) %}
        select * from orders
        {% if not loop.last -%} union all {% endif %}
    {% endfor %}
)

select * from final
```

this model takes 3-6 seconds, more than my 1 second timeout

running this model:

```bash
@lostmygithubaccount ➜ /workspaces/codyspace/triage/gcp_timeout (main ✗) $ dbt run -s test 
15:27:58  Running with dbt=1.3.0-b2
15:27:58  Found 6 models, 20 tests, 0 snapshots, 0 analyses, 301 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
15:27:58  
15:28:05  Concurrency: 8 threads (target='dev')
15:28:05  
15:28:05  1 of 1 START sql table model dbt_cody.test ..................................... [RUN]
15:28:08  1 of 1 ERROR creating sql table model dbt_cody.test ............................ [ERROR in 2.63s]
15:28:08  
15:28:08  Finished running 1 table model in 0 hours 0 minutes and 9.58 seconds (9.58s).
15:28:08  
15:28:08  Completed with 1 error and 0 warnings:
15:28:08  
15:28:08  Runtime Error in model test (models/test.sql)
15:28:08    Operation did not complete within the designated timeout.
15:28:08  
15:28:08  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
```

so I get the same error message you saw, and the model did seem to successfully timeout

our experiences diverge in that I can only see one job in the BigQuery UI (below are 3 separate runs this morning at different times):

![Image](https://user-images.githubusercontent.com/54814569/191301187-6437f060-4239-4706-9829-e68689ebcb4a.png)

from discussing with @jtcohen6 it sounded like dbt might be failing and retrying, but that's not the behavior I'm seeing. I think these job timeouts part of the code need some additional work outlined in https://github.com/dbt-labs/dbt-bigquery/issues/231

can you check if it's not from Airflow that you're seeing that second job triggered? or provide more details to reproduce this?

**Comment by atrbgithub** [comment] 2022-09-22 10:32
@lostmygithubaccount sorry for the confusion, we are running these jobs from airflow with a retry of 1 set, which is why we end up with multiple jobs running. 

What I would have expected to happen would be that when the timeout is reached in dbt, it would cancel the job in BigQuery. 

The tests you have run seem to prove that it doesn't cancel them (although as they don't run for very long I'm not sure it would of had chance to request BQ cancel the job). 

Is that the expected behaviour that when the timeout is reached, it allows the jobs to continue to run in BQ?

**Comment by lostmygithubaccount** [comment] 2022-09-22 21:09
@atrbgithub got it -- we should probably be cancelling them, that'd be my expectation as well. instead we're cancelling the dbt run

I'm going to close this issue as a duplicate in favor of https://github.com/dbt-labs/dbt-bigquery/issues/231, clearly link to this issue, and summarize the feedback. agreed on your interpretation of what should happen; it may not be work we pick up in the near future though

**Closed by lostmygithubaccount** 2022-09-22 21:09 UTC
Labels: enhancement
